# Generated by Django 2.2.6 on 2019-11-19 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='Titulo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
