# Generated by Django 2.2.6 on 2019-11-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191118_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Titulo',
            field=models.CharField(max_length=100),
        ),
    ]
